#!/bin/sh
set -e

# --- Configuration ---
GITHUB_REPO="Netajam/filedress"
INSTALL_DIR="${HOME}/.local/bin"
CMD_NAME="filedress"

# --- Helper Functions ---
echo_green() { printf "\033[0;32m%s\033[0m\n" "$1"; }
echo_error() { printf "\033[0;31mError: %s\033[0m\n" "$1" >&2; exit 1; }

# --- Main Logic ---
os=$(uname -s | tr '[:upper:]' '[:lower:]')
arch=$(uname -m)

case "$os" in
  linux)
    case "$arch" in x86_64) ;; *) echo_error "Unsupported architecture: $arch" ;; esac
    asset_os="linux"
    ;;
  darwin)
    case "$arch" in x86_64 | arm64) ;; *) echo_error "Unsupported architecture: $arch" ;; esac
    asset_os="macos"
    ;;
  *) echo_error "Unsupported OS: $os" ;;
esac

echo "Fetching latest version of ${CMD_NAME}..."
latest_tag=$(curl -s "https://api.github.com/repos/${GITHUB_REPO}/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
if [ -z "$latest_tag" ]; then
  echo_error "Could not fetch the latest release tag. Check repository name and ensure a release exists."
fi
echo_green "Latest version is ${latest_tag}"

asset_name="${CMD_NAME}-${asset_os}-x86_64.tar.gz"
download_url="https://github.com/${GITHUB_REPO}/releases/download/${latest_tag}/${asset_name}"

echo "Downloading from ${download_url}..."
temp_file=$(mktemp)
curl -L --progress-bar -o "$temp_file" "$download_url"

echo "Installing to ${INSTALL_DIR}..."
mkdir -p "$INSTALL_DIR"

# --- THE FIX IS HERE ---
# Extract just the binary to a temporary location, then move it.
# This is robust because it doesn't rely on complex tar flags.
temp_extract_dir=$(mktemp -d)
tar -xzf "$temp_file" -C "$temp_extract_dir"
# The file we want is at './filedress', so we find it and move it.
mv "${temp_extract_dir}/filedress" "${INSTALL_DIR}/"
# Clean up all temporary files and directories.
rm "$temp_file"
rm -rf "$temp_extract_dir"
# -----------------------

if ! command -v "${CMD_NAME}" >/dev/null; then
    echo "Warning: '${INSTALL_DIR}' is not in your PATH."
    echo "Please add 'export PATH=\"${INSTALL_DIR}:\$PATH\"' to your shell's startup file (e.g., ~/.bashrc)."
fi

echo_green "${CMD_NAME} installed successfully!"
"${INSTALL_DIR}/${CMD_NAME}" --version